# dummy stages to follow the template guidelines
stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup
  - extra


variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"

set variables:
  stage: .pre
  script:
    - apk add --no-cache git
    - echo GIT_VERSION=$(git describe) > variables.env
    - echo GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) >> variables.env
    - cat variables.env
  artifacts:
    reports:
      dotenv: variables.env


build:
  stage: build
  script:
    - export

# newjob:
#   stage: deploy
#   script:
#     - whoami

include: 
  - template: Auto-DevOps.gitlab-ci.yml
