# dummy stages to follow the template guidelines
stages:
  - build
  - test
  - deploy
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup
  - extra


variables:
  TEST_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"
  GIT_TEST: "$(git describe)"

setup:
  stage: .pre
  script:
    - apk add --no-cache git
    - echo $(git describe) > VERSION && echo $(git rev-parse --abbrev-ref HEAD) >> VERSION


build:
  stage: build
  script:
    - uname -a
    - apk add --no-cache git
    - export TEST=$(git describe)
    - export
    - whoami
    - cat VERSION

# newjob:
#   stage: deploy
#   script:
#     - whoami

include: 
  - template: Auto-DevOps.gitlab-ci.yml
