# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[default.extend-words]
muhc = "muhc"
mch = "mch"
# part of translation keys
2nd = "2nd"
# part of SerNum
ser = "ser"
# readby = "readby"
# SQL queries
tre = "tre"
tge = "tge"
varian = "varian"
# not worth it to fix
typ = "typ"
# chart specific
iy = "iy"
# French
raison = "raison"

[files]
extend-exclude = [
    "js/lib/**/*.js",
    "translate/locale-fr.json",
    "CHANGES",
]
