# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[default.extend-words]
muhc = "muhc"
mch = "mch"
nd = "nd"
# part of translation keys
2nd = "2nd"
2ND = "2ND"
# part of SerNum
ser = "ser"
# SQL queries
als = "als"
tge = "tge"
tre = "tre"
varian = "varian"
# not worth it to fix
typ = "typ"
ptdid = "ptdid"
ptd = "ptd"
complet = "complet"
# chart specific
iy = "iy"
# French
raison = "raison"
optionnel = "optionnel"

[files]
extend-exclude = [
    "js/lib/**/*.js",
    "translate/locale-fr.json",
    "CHANGES",
]
