services:
  redis:
      image: redis:7.2.3-alpine3.18
      environment:
        - TZ=America/Toronto
  app:
    build:
      context: .
      args:
        - PHP_ENV=development
    env_file:
      - .env
    ports:
      - 8082:8080
    depends_on:
      - redis
    environment:
      - TZ=America/Toronto
    volumes:
      - .:/var/www/html/
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/vendor
  cron:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html/
      - ./logs/opaladmin:/var/www/html/publisher/logs
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/vendor
    depends_on:
      - app
    # cron needs to run as root
    user: root
    entrypoint: ['/cron.sh']
