services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8082:8080
    volumes:
      - .:/var/www/html/
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/bower_components
      - /var/www/html/vendor
  cron:
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html/
      - ./logs/opaladmin:/var/www/html/publisher/logs
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/bower_components
      - /var/www/html/vendor
    depends_on:
      - app
    # cron needs to run as root
    user: root
    entrypoint: ['/cron.sh']
