version: '3'

services:
  app:
    build: .
    image: opalmedapps/opaladmin
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
      # don't overwrite existing content in these directories
      # needed if you want to manage these through the Docker image build process only
      - /var/www/html/node_modules
      - /var/www/html/bower_components
