version = 1


[[annotations]]
path = [
    "composer.json",
    "composer.lock",
    "package-lock.json",
    "package.json",
    "translate/locale-en.json",
    "translate/locale-fr.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    "CHANGES",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2016 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    "favicon.png",
    "images/opal_logo_transparent.png",
    "images/opal_logo_transparent_purple.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 Ackeem Joseph <ackeem.joseph@muhc.mcgill.ca>"
SPDX-License-Identifier = "LicenseRef-OpalTrademarks"


[[annotations]]
path = [
    "fonts/FontAwesome.otf",
    "fonts/fontawesome-webfont.eot",
    "fonts/fontawesome-webfont.svg",
    "fonts/fontawesome-webfont.ttf",
    "fonts/fontawesome-webfont.woff",
    "fonts/fontawesome-webfont.woff2",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2016 Dave Gandy <dave@fontawesome.io>"
SPDX-License-Identifier = "OFL-1.1"


[[annotations]]
path = [
    "css/lib/jquery-ui.css",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 jQuery Foundation and other contributors"
SPDX-License-Identifier = "LicenseRef-jQueryUI"


[[annotations]]
path = [
    "css/lib/ui.bootstrap.materialPicker.css",
    "js/lib/bootstrap/ui.bootstrap.materialPicker.js",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2015 Austin Andrews"
SPDX-License-Identifier = "MIT"


[[annotations]]
path = [
    "labs/diagram.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2023 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"
