version = 1


[[annotations]]
path = [
    "composer.json",
    "composer.lock",
    "package-lock.json",
    "package.json",
    "translate/locale-en.json",
    "translate/locale-fr.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = [
    "favicon.png",
    "images/opal_logo_transparent.png",
    "images/opal_logo_transparent_purple.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 Ackeem Joseph <ackeem.joseph@muhc.mcgill.ca>"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "fonts/FontAwesome.otf",
    "fonts/fontawesome-webfont.eot",
    "fonts/fontawesome-webfont.svg",
    "fonts/fontawesome-webfont.ttf",
    "fonts/fontawesome-webfont.woff",
    "fonts/fontawesome-webfont.woff2",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2016 Dave Gandy <dave@fontawesome.io>"
SPDX-License-Identifier = "OFL-1.1"


[[annotations]]
path = [
    "fonts/ProximaNovaSoft-Regular.eot",
    "fonts/ProximaNovaSoft-Regular.otf",
    "fonts/ProximaNovaSoft-Regular.svg",
    "fonts/ProximaNovaSoft-Regular.ttf",
    "fonts/ProximaNovaSoft-Regular.woff",
    "fonts/proxima-nova-soft-bold.eot",
    "fonts/proxima-nova-soft-bold.svg",
    "fonts/proxima-nova-soft-bold.ttf",
    "fonts/proxima-nova-soft-bold.woff",
]
precedence = "override"
# See:
#    - https://www.typewolf.com/proxima-nova-soft
#    - https://fontsfree.net/proxima-nova-soft-w03-semibold-font-download.html
#    - https://fonts.adobe.com/fonts/proxima-soft#fonts-section
#    - https://fonts.adobe.com/fonts/proxima-nova
SPDX-FileCopyrightText = "Copyright (C) 2010 Mark Simonson"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "images/bootstrap-colorpicker/alpha-horizontal.png",
    "images/bootstrap-colorpicker/alpha.png",
    "images/bootstrap-colorpicker/hue-horizontal.png",
    "images/bootstrap-colorpicker/hue.png",
    "images/bootstrap-colorpicker/saturation.png",
]
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "images/hospital-maps/qrCodes/DRC-Entrance-ODC.png",
    "images/hospital-maps/qrCodes/das.png",
    "images/hospital-maps/qrCodes/dasdsa.png",
    "images/hospital-maps/qrCodes/dsa.png",
    "images/hospital-maps/qrCodes/dsadad.png",
    "images/hospital-maps/qrCodes/dsadas.png",
    "images/hospital-maps/qrCodes/mapDS1_wait.png",
]
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "publisher/modules/Alias.pm",
    "publisher/modules/Announcement.pm",
    "publisher/modules/Api.pm",
    "publisher/modules/Appointment.pm",
    "publisher/modules/Configs.pm",
    "publisher/modules/Database.pm",
    "publisher/modules/Diagnosis.pm",
    "publisher/modules/Doctor.pm",
    "publisher/modules/Document.pm",
    "publisher/modules/EducationalMaterial.pm",
    "publisher/modules/EducationalMaterialControl.pm",
    "publisher/modules/Email.pm",
    "publisher/modules/FTP.pm",
    "publisher/modules/Filter.pm",
    "publisher/modules/LegacyQuestionnaire.pm",
    "publisher/modules/NotificationControl.pm",
    "publisher/modules/Patient.pm",
    "publisher/modules/PatientDoctor.pm",
    "publisher/modules/PatientLocation.pm",
    "publisher/modules/PatientsForPatients.pm",
    "publisher/modules/PostControl.pm",
    "publisher/modules/Priority.pm",
    "publisher/modules/PushNotification.pm",
    "publisher/modules/PushNotificationFromPHP.pm",
    "publisher/modules/Questionnaire.pm",
    "publisher/modules/Resource.pm",
    "publisher/modules/ResourceAppointment.pm",
    "publisher/modules/Staff.pm",
    "publisher/modules/Task.pm",
    "publisher/modules/TestResult.pm",
    "publisher/modules/TestResultControl.pm",
    "publisher/modules/TxTeamMessage.pm",
    "publisher/modules/Venue.pm",
]
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "images/template/clinician/waiting_room.png",
]
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"


[[annotations]]
path = [
    "css/lib/jquery-ui.css",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 jQuery Foundation and other contributors"
SPDX-License-Identifier = "LicenseRef-jQueryUI"


[[annotations]]
path = [
    "css/lib/ui.bootstrap.materialPicker.css",
    "js/lib/bootstrap/ui.bootstrap.materialPicker.js",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2015 Austin Andrews"
SPDX-License-Identifier = "MIT"
