angular.module('opalAdmin.controllers', [
	'opalAdmin.controllers.application',
	'opalAdmin.controllers.navigation',
	'opalAdmin.controllers.alias',
	'opalAdmin.controllers.alias.add',
	'opalAdmin.controllers.alias.edit',
	'opalAdmin.controllers.alias.delete',
	'opalAdmin.controllers.alias.log',
	'opalAdmin.controllers.post',
	'opalAdmin.controllers.post.add',
	'opalAdmin.controllers.post.edit',
	'opalAdmin.controllers.post.delete',
	'opalAdmin.controllers.post.log',
	'opalAdmin.controllers.educationalMaterial',
	'opalAdmin.controllers.educationalMaterial.add',
	'opalAdmin.controllers.educationalMaterial.edit',
	'opalAdmin.controllers.educationalMaterial.delete',
	'opalAdmin.controllers.educationalMaterial.log',
	'opalAdmin.controllers.hospitalMap',
	'opalAdmin.controllers.hospitalMap.add',
	'opalAdmin.controllers.hospitalMap.edit',
	'opalAdmin.controllers.hospitalMap.delete',
	'opalAdmin.controllers.notification',
	'opalAdmin.controllers.notification.add',
	'opalAdmin.controllers.notification.edit',
	'opalAdmin.controllers.notification.delete',
	'opalAdmin.controllers.notification.log',
	'opalAdmin.controllers.patient',
	'opalAdmin.controllers.patient.block',
	'opalAdmin.controllers.patient.edit',
	'opalAdmin.controllers.patientRegistration',
	'opalAdmin.controllers.patientRegistration.confirm',
	'opalAdmin.controllers.testResult',
	'opalAdmin.controllers.testResult.add',
	'opalAdmin.controllers.testResult.edit',
	'opalAdmin.controllers.testResult.delete',
	'opalAdmin.controllers.testResult.log',
	'opalAdmin.controllers.cron',
	'opalAdmin.controllers.cron.log',
	'opalAdmin.controllers.login',
	'opalAdmin.controllers.loginModal',
	'opalAdmin.controllers.patientActivity',
	'opalAdmin.controllers.account',
	'opalAdmin.controllers.user',
	'opalAdmin.controllers.user.add',
	'opalAdmin.controllers.user.edit',
	'opalAdmin.controllers.user.delete',
	'opalAdmin.controllers.user.log',
	'opalAdmin.controllers.installation',
	'opalAdmin.controllers.email',
	'opalAdmin.controllers.email.add',
	'opalAdmin.controllers.email.edit',
	'opalAdmin.controllers.email.delete',
	'opalAdmin.controllers.email.log',
	'opalAdmin.controllers.questionnaire',
	'opalAdmin.controllers.questionnaire.add',
	'opalAdmin.controllers.questionnaire.edit',
	'opalAdmin.controllers.questionnaire.delete',
	'opalAdmin.controllers.question',
	'opalAdmin.controllers.question.add',
	'opalAdmin.controllers.question.edit',
	'opalAdmin.controllers.question.delete',
	'opalAdmin.controllers.legacyQuestionnaire',
	'opalAdmin.controllers.legacyQuestionnaire.add',
	'opalAdmin.controllers.legacyQuestionnaire.edit',
	'opalAdmin.controllers.legacyQuestionnaire.delete',
	'opalAdmin.controllers.legacyQuestionnaire.log',
	'opalAdmin.controllers.diagnosisTranslation',
	'opalAdmin.controllers.diagnosisTranslation.add',
	'opalAdmin.controllers.diagnosisTranslation.edit',
	'opalAdmin.controllers.diagnosisTranslation.delete'
]);






